name: Vereficar site

on: [push]

jobs:
    Vereficar:
        runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Vereficar intex.html
          run: test -f intex.html